server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/secure
pipeline_stages:
  - regex:
      expression: '^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<host>[^ ]+)\s+(?P<program>[^:]+):.*Accepted password for (?P<user>\w+) from (?P<ip>[\d.]+)'
  - labels:
      timestamp:
      host:
      program:
      user:
      ip:
- job_name: DB
  static_configs:
  - targets:
      - localhost
    labels:
      job: db
      host: Test-02
      __path__: /data/pg_data/pgsql/15/data/log/*.log
  pipeline_stages:
   - regex:
      expression: 'FATAL: (?P<errmsg>.*)'
   - labels:
      errmsg: 
