global:
  resolve_timeout: 10m
templates:
  - 'template.tmpl'
receivers:
  - name: 'YDHN-telegram'
    telegram_configs:
      - api_url: https://api.telegram.org
        bot_token: '7018285945:AAHitDvGR_Ojk9ED50yV3IpwGRFGPas1Xdk'
        chat_id: -4587875318
        message: '{{ template "my_alert_template" . }}'
        disable_notifications: false
        http_config:
          follow_redirects: true
        send_resolved: true
        parse_mode: ""

  - name: 'bot-container'
    telegram_configs:
    - api_url: https://api.telegram.org
      bot_token: '6588801252:AAFJD4d1WW0L36mS_HfRlzTBIy3B7KJkIvc'
      chat_id: -4587875318
      message: '{{ template "cadvisor-alert" . }}'
      disable_notifications: false
      send_resolved: true
      parse_mode: ""

inhibit_rules:
  - source_match:
      severity: 'Khẩn cấp'
      alert_group: node_alert
    target_match:
      severity: 'Khẩn cấp'
      alert_group: cadvisor_alert
    equal: ['job', 'severity', 'instance', 'name']

route:
  continue: false
  group_by: ['job', 'severity', 'instance', 'name']
  group_interval: 1m
  group_wait: 5s
  repeat_interval: 5m
  receiver: "YDHN-telegram"

  routes:
    - match:
        job: BV-YDHN
        instance: 10.17.2.12:19100
        alert_group: node_alert  
      receiver: YDHN-telegram
      group_wait: 2s
    # - match:
    #     job: BV-YDHN
    #     instance: 10.0.38.22:9100
    #     alert_group: node_alert  
    #   receiver: YDHN-telegram
    #   group_wait: 2s
    # - match:
    #     job: BV-YDHN
    #     instance: 10.0.38.23:9100
    #     alert_group: node_alert  
    #   receiver: YDHN-telegram
    #   group_wait: 2s
    # - match:
    #     job: BV-YDHN
    #     instance: 10.0.2.24:9100
    #     alert_group: node_alert  
    #   receiver: YDHN-telegram
    #   group_wait: 2s
    # - match:
    #     job: BV-YDHN
    #     instance: 10.0.38.25:9100
    #     alert_group: node_alert  
    #   receiver: YDHN-telegram
    #   group_wait: 2s


    # - match:
    #     job: Container-YDHN
    #     alert_group: cadvisor_alert
    #     instance: 10.0.38.21:9092
    #   receiver: bot-container
    #   group_wait: 10s
    # - match:
    #     job: Container-YDHN
    #     alert_group: cadvisor_alert
    #     instance: 10.0.38.22:9092
    #   receiver: bot-container
    #   group_wait: 10s
    # - match:
    #     job: Container-YDHN
    #     alert_group: cadvisor_alert
    #     instance: 10.0.38.23:9092
    #   receiver: bot-container
    #   group_wait: 10s
    # - match:
    #     job: Container-YDHN
    #     alert_group: cadvisor_alert
    #     instance: 10.0.38.24:9092
    #   receiver: bot-container
    #   group_wait: 10s
    # - match:
    #     job: Container-YDHN
    #     alert_group: cadvisor_alert
    #     instance: 10.0.38.25:9092
    #   receiver: bot-container
    #   group_wait: 10s



    # - match:
    #     job: Container-YDHN
    #     alert_group: cadvisor_alert
    #     instance: 10.0.38.21:19092
    #   receiver: bot-container
    #   group_wait: 10s
    # - match:
    #     job: Container-YDHN
    #     alert_group: cadvisor_alert
    #     instance: 10.0.38.22:19092
    #   receiver: bot-container
    #   group_wait: 10s
    # - match:
    #     job: Container-YDHN
    #     alert_group: cadvisor_alert
    #     instance: 10.0.38.23:19092
    #   receiver: bot-container
    #   group_wait: 10s
    # - match:
    #     job: Container-YDHN
    #     alert_group: cadvisor_alert
    #     instance: 10.0.38.24:19092
    #   receiver: bot-container
    #   group_wait: 10s
#    - match:
#        job: Container-YDHN
#        alert_group: cadvisor_alert
#        instance: 10.0.38.25:19092
#      receiver: bot-container
#      group_wait: 10s
