global:
  resolve_timeout: 10m
templates:
  - 'template.tmpl'
receivers:
  - name: 'prometheus-telegram'
    telegram_configs:
      - api_url: https://api.telegram.org
        bot_token: '7018285945:AAHitDvGR_Ojk9ED50yV3IpwGRFGPas1Xdk'
        chat_id: -groupid
        message: '{{ template "my_alert_template" . }}'
        disable_notifications: false
        http_config:
          follow_redirects: true
        send_resolved: true
        parse_mode: ""

  - name: 'bot-container'
    telegram_configs:
    - api_url: https://api.telegram.org
      bot_token: '7018285945:AAHitDvGR_Ojk9ED50yV3IpwGRFGPas1Xdk'
      chat_id: -groupid
      message: '{{ template "cadvisor-alert" . }}'
      disable_notifications: false
      send_resolved: true
      parse_mode: ""

inhibit_rules:
  - source_match:
      severity: 'Khẩn cấp'
      alert_group: node_alert
    target_match:
      severity: 'Khẩn cấp'
      alert_group: cadvisor_alert
    equal: ['job', 'severity', 'instance', 'name']

route:
  continue: false
  group_by: ['job', 'severity', 'instance', 'name']
  group_interval: 1m
  group_wait: 5s
  repeat_interval: 5m
  receiver: "prometheus-telegram"


  
