version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    user: 'root'
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./data-prometheus-grafana/prometheus_data:/prometheus
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    network_mode: host
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    user: 'root'
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    network_mode: host
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: 'root'
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - ./data-prometheus-grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./grafana/config.monitoring
    network_mode: host
    depends_on:
      - prometheus
  msteams:
    image: nhlinh178/msteams-webhook:latest
    container_name: msteams
    user: 'root'
    restart: always
    volumes:
      - ./msteams/config.json:/app/config.json:ro
      - ./msteams/index.js:/app/index.js:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    volumes:
      - ./blackbox:/etc/blackbox/
    network_mode: host
    command:
      - '--config.file=/etc/blackbox/blackbox.yml'
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    network_mode: host
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki:/etc/loki
      - ./data-prometheus-grafana/loki_data:/loki
      - /etc/localtime:/etc/localtime:ro

