groups:
  - name: Redis
    rules:

    - alert: Redis Container Memory
      expr: container_memory_usage_bytes{name="system-grafana"} < 1.5e+10
      for: 1m
      labels:
        severity: critical
        app_type: redis
        category: memory
      annotations:
        summary: "Memory of redis container is high on {{ $labels.instance }} for more than 1 minutes"
        description: |
          HUY NG
          Memory of redis container is high on {{ $labels.instance }}, above 15GB