# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'Hospitals'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'rules/Jenkins.yml'
  - 'rules/CheckDomainStatus.yml'
  - 'rules/CheckPortContainer.yml'
  # - 'containers/DrAllen/DEAD/DrAllenServiceDead.yml'
  - "rules/NhiDongThanhPho.yml"
  # - "rules/phongkham40.yml"
  # - "rules/benhviene.yml"
  - "rules/benhvienquany110.yml"
  # - "rules/benhvienthanhhoa.yml"
  # - "rules/daihocy.yml"
  # - "rules/drallen.yml"
  # - "rules/benhviensaintpaul.yml"
  # - "rules/phongkhammediplus.yml"
  # - "rules/trungtamtimmach.yml"
  # - "rules/benhvienphoi.yml"
  # - "rules/benhvienbachmai.yml"
  # - "rules/phongkhamykhn.yml"
  # - "rules/ivirse.yml"
  # - "rules/isofhcare.yml"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"
      # basic_auth:
      #   username: admin
      #   password: daniel@0908

scrape_configs:
  - job_name: 'y-te-cong-cong'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Hệ Thống y tế công cộng
          - 183.80.255.19:19105

  - job_name: 'isofh-care'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Hệ Thống isofh-care
          - 3.0.34.197:9100
          - 13.213.154.221:9100
          - 13.215.174.69:9100
          - 13.229.40.73:9100
          - 54.151.146.66:19100
          - 54.251.13.109:9100
          - 3.0.58.192:19100

  - job_name: 'ivirse'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Hệ Thống ivirse
          - 103.9.211.17:9100
          - 103.9.211.44:9100
          - 103.9.211.57:9100
          - 103.9.211.82:9100
          - 103.9.211.87:9100
          - 103.9.211.120:9100
          - 103.9.211.175:9100
          - 103.9.211.108:9100

  - job_name: 'Benh-Vien-Bach-Mai'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện Bạch Mai
          - 10.0.1.34:19100

  - job_name: 'Y-Khoa-Ha-Noi'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Y Khoa Hà Nội
          - 113.190.44.104:19100


  - job_name: 'Nhi-Dong-Thanh-Pho'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Nhi Đồng Thành Phố
          - 10.0.2.38:9100
          - 10.0.2.40:9100
          - 10.0.2.41:9100
          - 10.0.2.42:9100
          - 10.0.2.43:9100
  
  - job_name: 'Phong-Kham-40'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Phòng Khám 40
          - 192.168.10.230:19100
          - 192.168.10.231:9100
          - 192.168.10.234:19100
          - 192.168.10.235:9100
          - 192.168.10.53:9187
          - 192.168.10.52:9187
          - 192.168.10.53:19100
          - 192.168.10.52:19100

  - job_name: 'Benh-Vien-E'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện E
          - '192.168.0.238:9100'
          - '192.168.0.245:9100'
          - '192.168.0.245:9187'
          - '192.168.0.244:9100'
          - '192.168.0.247:9100'
          - '192.168.0.242:9100'
          - '192.168.0.250:9100'
          - '192.168.0.251:9100'
  
  - job_name: 'Benh-Vien-110'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện QY 110
          - '10.110.55.11:9100'
          - '10.110.115.112:9100'
          - '10.110.115.89:9100'
          - '10.110.102.67:9100'
          - '10.110.115.110:9100'
          - '10.110.102.113:9100'
          - '10.110.102.88:9100'
          - '10.110.102.109:9100'

  - job_name: 'Benh-Vien-DK-ThanhHoa'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện Đa Khoa Thanh Hóa
          - '192.168.18.152:9100'
          - '192.168.18.153:9100'
          - '192.168.18.154:9100'
          - '192.168.18.155:9100'
          - '192.168.18.156:9100'
          - '192.168.18.157:9100'
          - '192.168.18.158:9100'
          - '192.168.18.160:9100'
          - '192.168.18.199:9100'
          - '192.168.18.200:9100'
          - '192.168.18.202:9100'
          - '192.168.18.203:9100'
          - '192.168.18.210:9100'
  
  - job_name: 'Dai-Hoc-Y'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện Đại Học Y
          - '192.168.55.161:9100'
          - '192.168.55.162:9100'
          - '192.168.55.163:9100'
          - '192.168.55.164:9100'
          - '192.168.55.168:9100'
          - '192.168.55.169:9100'
          - '192.168.55.173:9100'
          - '192.168.55.174:9100'
          - '192.168.55.175:9100'
          - '192.168.55.180:9100'
          - '192.168.55.182:9100'
          - '192.168.55.184:9100'
          - '192.168.55.190:9100'
          - '192.168.55.192:9100'
          - '192.168.55.197:9100'

  - job_name: 'Dr-Allen'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện DrAllen
          - '27.71.235.143:9100'
          - '27.71.235.144:9100'
          - '27.71.235.145:9100'

  - job_name: 'Saint-Paul'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện Saint Paul
          - '172.16.16.14:9100'
          - '172.16.16.15:9100'
          - '172.16.16.16:9100'
          - '172.16.16.17:9100'
          - '172.16.16.18:19100'
          - '172.16.16.19:19100'
          - '172.16.16.22:9100'
          - '172.16.16.23:9100'
          - '172.16.16.24:9100'
          - '172.16.16.28:9100'
          - '172.16.16.30:9100'
  
  - job_name: 'Mediplus'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Phòng Khám Mediplus
          - '10.3.0.17:9100'
          - '10.3.0.81:9100'
          - '10.3.0.82:9100'
          - '10.3.0.83:9100'
          - '10.3.0.84:9100'
          - '10.3.0.85:9100'
          - '10.3.0.95:9100'
          - '10.3.0.96:9100'

  - job_name: 'Benh-Vien-Phoi'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Bệnh Viện Phổi
          - '10.0.30.8:9100'
          - '10.0.30.9:9100'
          - '10.0.30.24:9100'
          - '10.0.30.30:9100'
          - '10.0.30.31:9100'
          - '10.0.30.32:9100'
          - '10.0.30.33:9100'
          - '10.0.30.35:9100'
          - '10.0.30.36:9100'
          - '10.0.30.40:9100'
          - '10.0.30.41:9100'
          - '10.0.30.45:9100'
          - '10.0.30.60:9100'
          - '10.0.30.61:9100'
          - '10.0.30.150:9100'
          - '10.0.30.152:9100'
          - '10.0.30.153:9100'
          - '10.0.30.200:9100'
          - '10.0.30.224:9100'

  - job_name: 'Trung-Tam-Tim-Mach'
    scrape_interval: 5s
    static_configs:
      - targets:
        # Trung Tâm Tim Mạch
          - '192.168.1.97:9100'
          - '192.168.1.225:19100'
          - '192.168.1.224:19100'
          - '192.168.1.224:9187'
          - '192.168.1.104:9100'
          - '192.168.1.106:9100'
          - '192.168.1.107:9100'
          - '192.168.1.223:9100'
          - '192.168.1.241:9100'
          - '192.168.1.242:9100'
          - '192.168.1.243:9100'
          - '192.168.1.250:9100'
# ========================================== PRIVATE ==========================================
  - job_name: 'Jenkins'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.131:19100']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
    basic_auth:
      username: admin
      password: daniel@0908

  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080
    static_configs:
      - targets: ['10.0.0.131:19093']

  # - job_name: 'docker-state'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['10.0.0.131:19092']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100


#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    dns_sd_configs:
#    - names:
#      - 'tasks.pushgateway'
#      type: 'A'
#      port: 9091

#     static_configs:
#          - targets: ['node-exporter:9100']

  - job_name: 'Check Domain Status'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets:
        - http://10.0.0.235:19400 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
  
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['10.0.0.235:19400']

  - job_name: blackbox_all
    metrics_path: /probe
    params:
      module: [ http_2xx ]  # Look for a HTTP 200 response.
    dns_sd_configs:
      - names:
          - example.com
          - prometheus.io
        type: A
        port: 443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/  # Make probe URL be like https://1.2.3.4:443/
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
      - source_labels: [__meta_dns_name]
        target_label: __param_hostname  # Make domain name become 'Host' header for probe requests
      - source_labels: [__meta_dns_name]
        target_label: vhost  # and store it in 'vh

  - job_name: 'Check_Port_Container'
    params:
      module:
      - tcp_connect
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /probe
    scheme: http
    static_configs:
    - targets:
      - 10.0.0.235:5000
      - 10.0.0.235:9087
    relabel_configs:
    - source_labels: [__address__]
      separator: ;
      regex: (.*)
      target_label: __param_target
      replacement: $1
      action: replace
    - source_labels: [__param_target]
      separator: ;
      regex: (.*)
      target_label: instance
      replacement: $1
      action: replace
    - separator: ;
      regex: (.*)
      target_label: __address__
      replacement: 10.0.0.101:9115
      action: replace