# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'Hospitals'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "rules/node-exporter-rules.yml"
  - "rules/cadvisor-rules.yml"
# alert
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - localhost:9093
           
scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
                         - "172.17.2.113:9100"
                         
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
                         - "172.17.2.114:9092"




