groups:
  - name: Alert_container
    rules:
      - alert: Container Down
        expr: (container_state_status{status="exited", id=~"/docker/.*", job="Cadvisor"} == 1 and (container_state_status{container_label_org_label_schema_name!=""} or container_state_status{container_label_com_docker_compose_version!=""} or container_state_status{container_label_org_opencontainers_image_version!=""})) or changes(container_start_time_seconds{id=~"/docker/.*",job="Cadvisor"}[30s]) > 4
        for: 1m
        labels:
          severity: Khẩn cấp
          job: "{{ $labels.job }}"
          alert_group: cadvisor_alert
          category: container
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "Container bị tắt"
          description: | 

                Container {{ $labels.name }} trên máy {{ $labels.instance }} đã bị tắt! Vui lòng kiểm tra lại!!!!

      - alert: RAM Container
        expr: (container_memory_working_set_bytes{id=~"/docker/.*",job="Cadvisor"}) / (container_spec_memory_limit_bytes{id=~"/docker/.*",job="Cadvisor"}) * 100 > 98 and (container_last_seen{container_label_org_label_schema_name!="",job="Cadvisor"} or container_last_seen{ container_label_com_docker_compose_version!="",job="Cadvisor"}) and ((container_memory_working_set_bytes{id=~"/docker/.*",job="Cadvisor"}) / (container_spec_memory_limit_bytes{id=~"/docker/.*",job="Cadvisor"}) * 100 <110)
        for: 1m
        labels:
          severity: Khẩn cấp
          job: "{{ $labels.job }}"
          alert_group: cadvisor_alert
          category: container
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "RAM container quá 90%"
          description: | 

                CONTAINER NAME: {{ $labels.name }}
                HOST: {{ $labels.instance }}
                Thông tin cụ thể:
                                RAM USED: {{ $value | printf "%.2f" }}% / 100%


      - alert: CPU Container
        expr: (sum(rate(container_cpu_usage_seconds_total{id=~"/docker/.*",job="Cadvisor"}[1m])) by (name, instance) *100) > 9000
        for: 1m
        labels:
          severity: Khẩn cấp
          job: "{{ $labels.job }}"
          alert_group: cadvisor_alert
          category: container
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "CPU container quá 9 Cores"
          description: | 

                CONTAINER NAME: {{ $labels.name }}
                HOST: {{ $labels.instance }}
                Thông tin cụ thể:
                                CPU USED : {{ $value | printf "%.2f" }}%
