groups:
  - name: Grafana
    rules:

    - alert: Grafana Container Cpu High
      expr: rate(container_cpu_usage_seconds_total{name="system-grafana"}[1m]) 
      for: 1m
      labels:
        severity: critical
        app_type: grafana
        category: cpu
      annotations:
        summary: "CPU of grafana container is high on {{ $labels.instance }}"
        description: |
          HUY NG
          CPU of grafana container is high for more than 1 minutes

    # - alert: Grafana Container Memory
    #   expr: container_memory_usage_bytes{name="system-grafana"} < 1.5e+10
    #   for: 1m
    #   labels:
    #     severity: critical
    #     app_type: grafana
    #     category: memory
    #   annotations:
    #     summary: "Memory of grafana container is high on {{ $labels.instance }} for more than 1 minutes"
    #     description: |
    #       HUY NG
    #       Memory of grafana container is high on {{ $labels.instance }}, above 15GB